version: "3"
services:
  db:
    build: ./docker/msSql
    container_name: "MsSqlTest"
    ports:
    - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password123!
      - MSSQL_PID=Express
